apiVersion: v1
kind: Secret
metadata:
  annotations:
    archon.kubeup.com/alias: ca
    archon.kubeup.com/csr: |-
      {
        "CN": "k8s-ca",
        "hosts": [
          "k8s-ca"
        ],
        "key": {
          "algo": "rsa",
          "size": 2048
        },
        "names": [
          {
            "C": "US",
            "L": "CA",
            "ST": "San Francisco"
          }
        ]
      }
    archon.kubeup.com/status: Approved
    archon.kubeup.com/type: ca
  name: k8s-ca
type: Opaque
